# Generated by Django 2.2.5 on 2019-09-29 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirbSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
