# Generated by Django 2.2.5 on 2019-09-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birbsighting',
            options={'ordering': ['-date']},
        ),
    ]
