# Generated by Django 2.2.5 on 2019-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0002_auto_20190929_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='birbsighting',
            name='comments',
            field=models.TextField(default='pop'),
            preserve_default=False,
        ),
    ]
