# Generated by Django 2.2.5 on 2019-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0004_auto_20191003_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
