# Generated by Django 2.2.5 on 2019-10-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0005_species_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birbsighting',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birbsighting', to='dataapis.Species'),
        ),
    ]
