# Generated by Django 2.2.6 on 2019-10-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0008_auto_20191003_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birbsighting',
            name='picture',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
